export const newsData = [
  {
    id: 1,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    image: 'https://res.cloudinary.com/dqaerysgb/image/upload/v1650308633/img-3_osvtro.jpg',
    date: '2 days ago',
    author: 'James Bond',
    avatar: require('../'),
    content: 'Lorem ipsum dolor sit amet ',
  },
  {
    id: 2,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    image:
      'https://res.cloudinary.com/dqaerysgb/image/upload/v1647972916/can-tinder-make-you-hinder-dating-apps-can-take-a-toll-on-your-mental-health_blhzxx.jpg',
    date: '2 days ago',
    author: 'Lorem ipsum dolor sit amet',
    avatar: require('../'),
    content: 'Lorem ipsum dolor sit amet ',
  },
  {
    id: 3,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    image: 'https://res.cloudinary.com/dqaerysgb/image/upload/v1635399087/Cuban-Food-1_mydd1f.jpg',
    date: '2 days ago',
    author: 'Lorem ipsum dolor sit amet',
    avatar: require('../'),
    content: 'Lorem ipsum dolor sit amet ',
  },
  {
    id: 4,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    image: 'https://res.cloudinary.com/dqaerysgb/image/upload/v1635399413/picWmxBlt_fx19jk.jpg',
    date: '2 days ago',
    author: 'Lorem ipsum dolor sit amet',
    avatar: require('../'),
    content: 'Lorem ipsum dolor sit amet ',
  },
  {
    id: 5,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    image: 'https://res.cloudinary.com/dqaerysgb/image/upload/v1635360680/mexico_h9dcjv.jpg',
    date: '2 days ago',
    author: 'Lorem ipsum dolor sit amet',
    avatar: require('../'),
    content: 'Lorem ipsum dolor sit amet ',
  },
  {
    id: 6,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    image: 'https://res.cloudinary.com/dqaerysgb/image/upload/v1635360679/italian-food_jsa7c0.jpg',
    date: '2 days ago',
    author: 'Lorem ipsum dolor sit amet',
    avatar: require('../'),
    content: 'Lorem ipsum dolor sit amet ',
  },
];
